version: "3.5"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "sbdl"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password123"
      POSTGRES_EXTENSIONS: pg_trgm
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    ports:
      - "9200:9200"
