---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Ship binary to server
      synchronize:
        src: ../target/release/sb_dl
        dest: '{{app_root}}/sb_dl'
        recursive: yes
        delete: yes

    - name: Ship config to server
      synchronize:
        src: ../config.yaml
        dest: '{{app_root}}/config.yaml'
        recursive: yes
        delete: yes

    - name: Ship geyser stream service to server
      template:
        src: "geyser_stream.service.j2"
        dest: "/etc/systemd/system/geyser_stream.service"
        mode: 0755

    - name: Ship bigtable downloader service to server
      template:
        src: "bigtable_downloader.service.j2"
        dest: "/etc/systemd/system/bigtable_downloader.service"
        mode: 0755

    - name: Ship backfiller service to server
      template:
        src: "backfiller.service.j2"
        dest: "/etc/systemd/system/backfiller.service"
        mode: 0755

    - name: Ship transfer flow api service to server
      template:
        src: "transfer_flow_api.service.j2"
        dest: "/etc/systemd/system/transfer_flow_api.service"
        mode: 0755

    - name: Configuring geyser stream service
      service:
        name: geyser_stream
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Configuring bigtable downloader service
      service:
        name: bigtable_downloader
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Configuring backfiller service
      service:
        name: backfiller
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Configuring transfer flow api service
      service:
        name: transfer_flow_api
        state: restarted
        enabled: true
        daemon_reload: true